rc_customer:
    resource: |
        alias: rc.customer
        section: app
        templates: RCWebBundle:Crud
        except: []
        grid: rc_customer
        vars:
            all:
                subheader: red_carpet.grid.customer # define a translation key for your entity subheader
            index:
                icon: 'file image outline' # choose an icon that will be displayed next to the subheader
    type: sylius.resource
