sylius_resource:
    resources:
        rc.customer:
            classes:
                model: RC\CustomerBundle\Entity\Customer
                form: RC\Bundle\CustomerBundle\Form\Type\RegistrationType