# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    RC\UserBundle\:
        resource: '../../src/RC/UserBundle/*'

    RC\CustomerBundle\:
        resource: '../../src/RC/CustomerBundle/*'