# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    RC\CoreBundle\:
        resource: '../../src/RC/CoreBundle/*'

    RC\CoreBundle\EventListener\UuidListener:
        tags:
          - { name: doctrine.event_listener, event: prePersist }

    RC\UserBundle\:
        resource: '../../src/RC/UserBundle/*'

    RC\CustomerBundle\:
        resource: '../../src/RC/CustomerBundle/*'
