rc_homepage:
    path:     /
    defaults: { _controller: RCWebBundle:Default:index }

rc_frontend:
    prefix: /app
    resource: "@RCWebBundle/Resources/config/routing/app/main.yml"

rc_backend:
    prefix: /admin
    resource: "@RCWebBundle/Resources/config/routing/admin/main.yml"