rc_customer:
    resource: |
        alias: rc.customer
        identifier: uuid
        section: admin
        redirect: index
        templates: RCWebBundle:Crud
        except: []
        grid: rc_customer
        criteria:
            uuid: $uuid
        vars:
            all:
                subheader: rc.grid.customer # define a translation key for your entity subheader
            index:
                icon: 'file image outline' # choose an icon that will be displayed next to the subheader
    type: sylius.resource
